### ISSUE TITLE
program crashes after min 29

### ISSUE THREAD

**Issue by siropregno** [floh22/LeagueBroadcastHub#143] opened 2022-04-25 12:53 UTC
hi! anyone with the same problem? thank you guys

**Comment by Coow** [comment] 2022-04-25 12:57
The crash seems to appear whenever you go beyong 29 minutes or so, and you try to bring up the GoldGraph. 
Unfortunately I havent been able to figure out why that is the case

**Comment by floh22** [comment] 2022-05-26 13:45
duplicate of #134

**Closed as completed by floh22** 2022-05-26 13:45 UTC
Labels: bug
