### ISSUE TITLE
Crashing after trying turn on "Gold Graph"

### ISSUE THREAD

**Issue by OrionCodeDev** [floh22/LeagueBroadcastHub#4] opened 2021-05-08 22:13 UTC
Hey bro i saw v2 LBH and i tested it, first of all, i wanna say thanks for your work, it's awesome bro <3

I have one small problem with Gold Graph instantly crashing app when i click on them. I added LiveEvents etc. Any idea whats wrong or how i can test it to catch the problem?
Best Regards

**Comment by OrionCodeDev** [comment] 2021-05-08 22:14
Some logs:
```
[00-14-07] Game Loaded
[00-14-07] Game Paused
[00-14-07] LiveEventAPI Connected
[00-14-07] Game Resumed
[00-14-08] Init Team data
[00-14-08] [WARNING] Sequence contains no matching element
[00-14-09] [WARNING] Sequence contains no matching element
[00-14-09] [WARNING] Sequence contains no matching element
```

**Comment by OrionCodeDev** [comment] 2021-05-08 22:31
And also i don't wanna spam in your repo, so i wanna report one bug:
[https://i.imgur.com/uUTmMKN.png](https://i.imgur.com/uUTmMKN.png)
For example it's will be better when it's will rounded Gold amount diff on baron/elder timer. Now it's out of box
Regards

**Comment by floh22** [comment] 2021-05-09 00:45
Hey. The issue was caused by the fact that there was no data yet, you had the gold graph on at 00:00. Added a catch for this case
Should be fixed in 3c5d943136b58123a5bb965242695cc95adf2c84. Please tell me if it has also fixed it for you

Also, please feel free to open an issue per actual issue. Its easier for me to track, and thats why this is here. If theres a bunch of issues, go ahead and spam me haha.

Side note, the UI is not nearly finished, its in a rather rough shape atm. I wanted to get the features I had before complete and then move repos away from my private one. I will be adding missing features over the coming weeks now that the rewrite and move to memory reading is complete

**Comment by OrionCodeDev** [comment] 2021-05-09 11:26
Hm still seems looking like crashing, now be more agressive like when i turned it on the app crashed and when i trying to run it retry it;'s instantly crashing. All except that working fine like baron timers now it's really cool <3.

**Comment by floh22** [comment] 2021-05-09 12:08
Ok. Can you please describe what steps you take in the exact order to reproduce the issue?
It may also help if you provide a replay file of the game in question. Maybe some champion name is different in memory/in league API

**Comment by OrionCodeDev** [comment] 2021-05-09 20:18
Yeah sure bro,
For example: download latest version from git release -> run and wait for downlad all -> LBH be runned -> enter to game -> wait few minutes/more than 10-15 minutes -> Click on "Gold Graph" -> app crashing

example match: https://www.leagueofgraphs.com/api/spectate/WTJJei9NMFFVeFFERXZFTDR0WjVUQlFwQzVobTl6TWc0bUxhQlI0UmNDc2JTQzRBNWQ0SXRyY0tXcUpMYVNPZVpBUHJ0VVVtbmRSbks1bkVSSm9IQlE9PQ==

**Comment by floh22** [comment] 2021-05-09 22:37
Im having issues opening the replay file. Can you send it through github?

**Comment by OrionCodeDev** [comment] 2021-05-09 22:43
GitHub not support bat ext. I uploaded it to Gdrive: https://drive.google.com/file/d/1SDUUnJPM1QenqNjfLvH1_f4wx2ByLMtE/view?usp=sharing

**Comment by floh22** [comment] 2021-05-09 23:37
The problem I am having is that the bat produces a black screen from league on 3 separate PCs. It would be best if you could share the .rofl file directly. 

Also, could you tell me which champions are in the game? Then I can test myself.

**Comment by floh22** [comment] 2021-05-23 16:30
closed due to inactivity

**Closed as completed by floh22** 2021-05-23 16:30 UTC
