### ISSUE TITLE
Gold Graph errors

### ISSUE THREAD

**Issue by ChronoBrake** [floh22/LeagueBroadcastHub#2] opened 2021-04-07 12:26 UTC
Hey i tested LBG with OCR and gold graph not working correctly
Here is image:  https://i.imgur.com/dgP4YlK.png

Best regards

**Comment by floh22** [comment] 2021-04-10 16:24
Hey. sorry for the late reply. Can you send me the client gold graph for this game and at what time ingame this error happend? There is a bug sometimes where if only red side or only blue side have a gold advantage, the gold graph breaks. I tried fixing it but it seems there might be some situations where it still happens

**Comment by ChronoBrake** [comment] 2021-04-22 09:13
Nvm it's starting working fine after change some firewall rules. You already saw new LiveEvents API bro? You have update this tool in nearly future ? I waiting for new features from you <3
Best Regards

**Comment by floh22** [comment] 2021-04-22 12:46
Hey. Glad the issue is sorted. Going to close this issue for now.

As for the new API, im working on it. It's been barely 48 hours since it was first found, so it's going to take a bit.

**Closed by floh22** 2021-04-22 12:46 UTC
Labels: bug
