### ISSUE TITLE
[BUG]Gold is not shown，Gold Graph，Champion exceptions are not displayed

### ISSUE THREAD

**Issue by Khhd1** [floh22/LeagueBroadcastHub#13] opened 2021-05-28 02:51 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Material**
* If applicable, add screenshots to help explain your problem.
* Include Logs of when the error occured, as well as the crash log if applicable
* Please include the .rofl replay file if the issue was present while spectating

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 20H1 (May 2020 Update) Build 19041]

**Additional context**
![EXP CHAMPION BUG](https://user-images.githubusercontent.com/82941693/119922541-95935500-bfa2-11eb-9509-49416bbea619.png)
![Gold bug](https://user-images.githubusercontent.com/82941693/119922544-96c48200-bfa2-11eb-9909-349698549d84.png)
![Gold bug2](https://user-images.githubusercontent.com/82941693/119922545-975d1880-bfa2-11eb-9500-162f28679fe0.png)
![Gold bug3](https://user-images.githubusercontent.com/82941693/119922549-97f5af00-bfa2-11eb-87f9-eb826101c482.png)

**Comment by OrionCodeDev** [comment] 2021-05-28 06:17
I responded here in issue #12, but it's already closed. I will forward it here. For me all except that two pictures working fine, so you must doing something wrong bro. 

https://github.com/floh22/LeagueBroadcastHub/issues/12#issuecomment-850008607

Best Regards

**Comment by floh22** [comment] 2021-05-28 17:37
Duplicate of #7 

This project will not work fully with the CN client. Memory locations, structure, and security are different on that client. 

Any information that is gathered using memory cannot be supported in CN. This includes xp, gold, position.

**Closed as completed by floh22** 2021-05-28 17:37 UTC
Labels: bug
