### ISSUE TITLE
Can you indicate the time left until the object is created?

### ISSUE THREAD

**Issue by 21Broo** [floh22/LeagueBroadcastHub#113] opened 2022-01-20 12:28 UTC
![ojtimer](https://user-images.githubusercontent.com/71747410/150338188-1d7e95fb-670b-429f-b1e1-397a1253599e.png)
As shown in the picture above, can you display the time left until object creation? I'm not talking about how to display it as the basic function of the roll. I wonder if I can customize it like the picture.

**Comment by floh22** [comment] 2022-01-20 13:12
duplicate of #82 

Currently I do not know of a reliable way to get the type of the next dragon spawning, so I cannot implement this feature

**Closed as completed by floh22** 2022-01-20 13:12 UTC

**Comment by 21Broo** [comment] 2022-01-21 11:23
> duplicate of #82
> 
> Currently I do not know of a reliable way to get the type of the next dragon spawning, so I cannot implement this feature

oh i see thanks i'll find a way myself
