### ISSUE TITLE
[BUG] Report many bugs

### ISSUE THREAD

**Issue by AzureAstral** [floh22/LeagueBroadcastHub#283] opened 2023-08-02 14:51 UTC
Hey, 

I use all the time this software so, here is an exhaustive list of the errors that I could encounter during the use 👍 

- Despite the good offsets, the dragons that appear in the timer are not the right ones sometimes
- the draft does not work 3 times / 4
- The "Baron Powerplay" counter is too difficult to move
- Sometimes the Inhibitor counter background does not appear correctly when it is an image

Thx ! :D

**Comment by overkido** [comment] 2023-08-03 12:53
* O contador "Baron Powerplay" é muito difícil de mover.

here in mine I configure it as I want it is very simple in fact, the drakes bug and inhibitors backgroud yes bug I do the live with the conf. open so you can show it when it doesn't show
![image](https://github.com/floh22/LeagueBroadcast/assets/89580284/305d8ba4-4c5c-4c90-be99-65c5067c1f64)

inhibitors and drakes I move and configure as I wanted, but their bugs don't have much to do.
![image](https://github.com/floh22/LeagueBroadcast/assets/89580284/8e8dc9a9-0c0c-4bea-b5f2-8c3ed3d86e60)

**Comment by AzureAstral** [comment] 2023-08-03 13:02
> * O contador "Baron Powerplay" é muito difícil de mover.
> 
> here in mine I configure it as I want it is very simple in fact, the drakes bug and inhibitors backgroud yes bug I do the live with the conf. open so you can show it when it doesn't show ![image](https://user-images.githubusercontent.com/89580284/258115806-305d8ba4-4c5c-4c90-be99-65c5067c1f64.png)
> 
> inhibitors and drakes I move and configure as I wanted, but their bugs don't have much to do. ![image](https://user-images.githubusercontent.com/89580284/258116762-8e8dc9a9-0c0c-4bea-b5f2-8c3ed3d86e60.png)

Wow this is awesome ! Can u explain how u do this with the baron powerplay ? U have an timer for nashor too or u use the timer official ?

**Comment by overkido** [comment] 2023-08-03 13:47
> 

I don't have the nashor timer, I've looked for it and never found the api, but I can help without a problem.

**Comment by floh22** [comment] 2023-08-11 01:39
At least the inhib is fixed in the latest release. The rest will most likely not be addressed.

I cannot reproduce the issues with dragons, if you manage to reliably reproduce it, please record a video of the game state and the overlay, or send the replay.

**Closed as completed by floh22** 2023-08-11 01:39 UTC
Labels: bug
