### ISSUE TITLE
[FEATURE] Use on tournament server.

### ISSUE THREAD

**Issue by 18y45** [floh22/LeagueBroadcastHub#67] opened 2021-09-01 13:57 UTC
Hello,
I am making this message for a feature that will allow you to use the program (or what is possible) on the tournament server

More and more riot gives TR accesses
for amateur tournaments I think it would be a good idea.

thanks in advance

**Comment by floh22** [comment] 2021-09-01 14:10
Duplicate of #3

**Closed as completed by floh22** 2021-09-01 14:10 UTC
Labels: duplicate, enhancement
