### ISSUE TITLE
[FEATURE] Add time respawn dragon, baron on the overlay

### ISSUE THREAD

**Issue by Nezumi2711** [floh22/LeagueBroadcastHub#111] opened 2022-01-14 12:12 UTC
Can you add the time respawn for dragon and baron so I can customize the layout like this? Thanks for read.
![image](https://user-images.githubusercontent.com/73208452/149513565-35d320c5-ba59-4ff4-9415-3223700c1e81.png)

**Comment by floh22** [comment] 2022-01-14 14:35
Duplicate of #82

**Closed as completed by floh22** 2022-01-14 14:35 UTC
Labels: enhancement
