### ISSUE TITLE
[BUG] Program crashes on load - suspect that it is new patch - 12.21

### ISSUE THREAD

**Issue by benholness** [floh22/LeagueBroadcastHub#197] opened 2022-11-02 19:33 UTC
When I open the program after a new patch, it doesn't want to load at all.

Can someone provide some guidance on how to fix it when a new patch is available? Is there a file I need to tweak?

**Comment by floh22** [comment] 2022-11-02 20:54
duplicate of #196

**Closed as completed by floh22** 2022-11-02 20:54 UTC
Labels: bug, duplicate
